name       : kbd
version    : 2.0.3
release    : 1
source     :
    - ftp://ftp.kernel.org/pub/linux/utils/kbd/kbd-2.0.3.tar.xz : 7a899de1c0eb75f3aea737095a736f2375e1cbfbe693fc14a3fe0bfb4649fb5e
license    : GPL-2.0
component  : system.utils
summary    : Linux keyboard tools
description: |
    Tools for managing Linux console (Linux console, virtual terminals, keyboard, etc.) – mainly, what they do is loading console fonts and keyboard maps.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
