name       : kbd
version    : 2.5.1
release    : 5
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.5.1.tar.xz : ccdf452387a6380973d2927363e9cbb939fa2068915a6f937ff9d24522024683
license    : GPL-2.0-or-later
component  : system.utils
summary    : Linux keyboard tools
description: |
    Tools for managing Linux console (Linux console, virtual terminals, keyboard, etc.) – mainly, what they do is loading console fonts and keyboard maps.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
