name       : kbd
version    : 2.6.1
release    : 6
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.6.1.tar.xz : 2eb6c6c972be9589bab733275bf020beb5f644d5f9439737920e701af6cf3485
license    : GPL-2.0-or-later
component  : system.utils
summary    : Linux keyboard tools
description: |
    Tools for managing Linux console (Linux console, virtual terminals, keyboard, etc.) – mainly, what they do is loading console fonts and keyboard maps.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
