name       : kbd
version    : 2.0.4
release    : 2
source     :
    - https://www.kernel.org/pub/linux/utils/kbd/kbd-2.0.4.tar.xz : 5fd90af6beb225a9bb9b9fb414c090fba53c9a55793e172f508cd43652e59a88
license    : GPL-2.0
component  : system.utils
summary    : Linux keyboard tools
description: |
    Tools for managing Linux console (Linux console, virtual terminals, keyboard, etc.) – mainly, what they do is loading console fonts and keyboard maps.
builddeps  :
    - pkgconfig(check)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
